### ISSUE TITLE
testing new homepage

### ISSUE THREAD

**Issue by atherdon** [atherdon/snipts#15]
[hackernoon homepage v2_ brainstorm numero uno.pdf](https://github.com/atherdon/snipts/files/5966986/hackernoon.homepage.v2_.brainstorm.numero.uno.pdf)

**Comment by atherdon** [comment]
Моя начальница сделала примерный набросок новой homepage. 
я бы хотел ее замотивировать, чтобы она и дальше думала о нововведениях на сайте.
для этого нам нужно сделать быструю версию, которая будет похожа на набросок, а пока начальница будет давать комментарии - мы уже закончим полировать эту страницу.

под быстрой версией я понимаю: текст ставим lorem ipsum, картинки ставим любым placeholder.
еще я думал сделать копию нашего текущего header и уже его перепилить под этот дизайн.

header является sticky как я понял - поэтому он и отображается на каждом отдельном листе.
![image](https://user-images.githubusercontent.com/1469198/107849031-1ddd5800-6e01-11eb-8796-f76bfb12b7d3.png)

а внизу разные разделители как дополнительная реклама
![image](https://user-images.githubusercontent.com/1469198/107849043-29c91a00-6e01-11eb-8340-b4a44e128f75.png)

**Comment by F1reMonster** [comment]
додано

**Comment by F1reMonster** [comment]
> еще я думал сделать копию нашего текущего header и уже его перепилить под этот дизайн.

додав версію із таким хедером, index-v2.html

**Comment by atherdon** [comment]
смотрю

**Comment by atherdon** [comment]
@F1reMonster пошел показывать начальнице - спасибо!

**Comment by atherdon** [comment]
закрою пока эту задачу, а фидбек уже перенесу в новый таск
